# Generated by Django 4.0.6 on 2022-07-23 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('siglas', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('valor_bien', models.DecimalField(decimal_places=2, max_digits=100)),
                ('numero_cuartos', models.IntegerField()),
                ('valor_mensual', models.DecimalField(decimal_places=2, max_digits=100)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='los_barrios2', to='catastro.barrio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='las_casas2', to='catastro.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('valor_bien', models.DecimalField(decimal_places=2, max_digits=100)),
                ('color', models.CharField(max_length=20)),
                ('numero_cuartos', models.IntegerField()),
                ('numero_pisos', models.IntegerField()),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='los_barrios', to='catastro.barrio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='las_casas', to='catastro.persona')),
            ],
        ),
    ]
