# Generated by Django 4.0.6 on 2022-08-11 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='los_propietarios', to='catastro.persona'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='los_propietarios2', to='catastro.persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(max_length=50),
        ),
    ]
