// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgAby09DLJeq6w-pb1gHMF12utv0vUro0',
    appId: '1:125015530737:web:f75f8e22eceb58c9cc1d50',
    messagingSenderId: '125015530737',
    projectId: 'doggy-9c368',
    authDomain: 'doggy-9c368.firebaseapp.com',
    storageBucket: 'doggy-9c368.appspot.com',
    measurementId: 'G-2C5BK9X5LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj6z92fRRfdHvbgMtb3UE1Ik9viF7cWW8',
    appId: '1:125015530737:android:c3fdef633f0c1e02cc1d50',
    messagingSenderId: '125015530737',
    projectId: 'doggy-9c368',
    storageBucket: 'doggy-9c368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP1YtMHvacOs_A2qsE_ojh2NhVrvQd5p4',
    appId: '1:125015530737:ios:83868de9507938ddcc1d50',
    messagingSenderId: '125015530737',
    projectId: 'doggy-9c368',
    storageBucket: 'doggy-9c368.appspot.com',
    iosClientId: '125015530737-ki7h9evp3fqealj6cmtg0upe8lpt027g.apps.googleusercontent.com',
    iosBundleId: 'com.example.doggy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP1YtMHvacOs_A2qsE_ojh2NhVrvQd5p4',
    appId: '1:125015530737:ios:83868de9507938ddcc1d50',
    messagingSenderId: '125015530737',
    projectId: 'doggy-9c368',
    storageBucket: 'doggy-9c368.appspot.com',
    iosClientId: '125015530737-ki7h9evp3fqealj6cmtg0upe8lpt027g.apps.googleusercontent.com',
    iosBundleId: 'com.example.doggy',
  );
}
